#!/bin/bash

systemctl mask systemd-backlight@leds\:dell\:\:kbd_backlight.service
systemctl enable --now nohang-desktop.service
nohang --memload
sudo systemctl enable ananicy
sudo systemctl start ananicy

