#!/bin/bash

sudo pacman -S bspwm \
  dunst \
  sxhkd \
  lxappearance \
  rofi \
  pamixer \
  alacritty \
  mpd \
  ncmpcpp \
  kitty \
  kvantum \
  feh \
  stow \
  okular \
  xdo \
  xorg-xinit \
  picom \
  firefox \
  xorg python-pip \
  ttf-sarasa-gothic \
  libnotify \
  yarn \
  neovim \
  playerctl \
  xdg-user-dirs \
  kdeconnect \
  ueberzug \
  yt-dlp \
  blueman \
  sshfs \
  vlc \
  gedit \
  maim \
  cowfortune \
  lsd \
  lynx \
  zathura \
  unzip \
  npm \
  zathura-djvu \
  zathura-ps \
  zathura-pdf-mupdf \
  xsel \
  tree \
  dmenu \
  sxiv \
  ffmpeg \
  clipmenu \
  krusader \
  zip \
  ansible \
  catdoc \
  docx2txt \
  ttf-dejavu \
  conky \
  lazygit \
  python-beautifulsoup4\
  python-requests \
  archlinux-keyring \
  geckodriver \
  newsboat &&
  pip install dbus-python && 
  pip install pynvim
