#!/bin/bash

yay -S i3lock-color \
  polybar \
  pulseaudio-ctl \
  ytfzf \
  whatsdesk \
  ani-cli-git \
  qt5ct \
  papirus-folders-nordic \
  ttf-iosevka \
  lf \
  webtorrent-cli \
  python-lxml \
  ly \
  ananicy \
  nohang \
  epub-thumbnailer-git \
  ttf-fira-code \
  mono \
  notify-send-py
