#!/bin/bash

yay -S i3lock-color \
  polybar \
  pipewire \
  btop \
  mpdris2 \
  siji-git \
  pipewire-pulse \
  ytfzf \
  tdrop \
  whatsdesk \
  qt5ct \
  papirus-folders-nordic \
  ttf-iosevka \
  lf \
  webtorrent-cli \
  nordic-darker-theme \
  ly \
  epub-thumbnailer-git \
  ttf-fira-code \
  mono 

sudo systemctl enable ly.service
