#!/bin/sh

# Wallpaper
feh --randomize --bg-scale ~/.wallpapers/* 

# Kill Applications
pkill -f firefox
pkill -f kdeconnectd
pkill -f polybar
pkill kdeconnect-indicator
pkill -f WhatsDesk
pkill -f WhatsDesk

# Polybar
~/.config/polybar/launch.sh &

whatsdesk &

# Applications
blueman-applet &                 #Bluetooth Manager Applet

clipmenud &                      #Clipmenu Daemon

/usr/lib/kdeconnectd &           #KDE Connect 

kdeconnect-indicator &           #KDE Connect Applet
kdeconnect-indicator &           #KDE Connect Applet

# Keyboard Layout
setxkbmap -layout us,'us(dvorak)' -option grp:toggle &

# Conky
conky -c ~/.config/conky/todo/todo.conf

# MPD
~/.scripts/mpd_start &
