#!/usr/bin/env bash

# Wallpaper
feh --bg-scale ~/.wallpapers/evening-sky.png &

# Kill Applications
pkill -f kdeconnectd
pkill -f polybar
pkill kdeconnect-indi
pkill -f WhatsDesk
pkill conky
pkill emacs
pkill spotify

# Polybar
~/.config/polybar/launch.sh &

# Applications
blueman-applet &                 #Bluetooth Manager Applet
whatsdesk &
clipmenud &                      #Clipmenu Daemon
/usr/lib/kdeconnectd &           #KDE Connect 
/usr/bin/kdeconnect-indicator            #KDE Connect Applet
emacs --daemon &                 #Emacs Daemon
flameshot &

# Keyboard Layout
setxkbmap -layout us,'us(dvorak)' -option grp:toggle &

# Conky

# MPD
~/.scripts/mpd_start &
